# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
require 'pry'

class SumOfEvenFib

  def initialize(limit)
    @limit = limit
    @fib = [1, 2]
  end

  def full_fibonacci
    while @fib.last(2).inject(:+) < @limit
      @fib << @fib.last(2).inject(:+)
    end
  end

  def sum_of_evens
    full_fibonacci
    @fib.select {|n| n % 2 == 0}.inject(:+)
  end
end

puts "enter limit"
limit = gets.strip.to_i
puts "answer is #{SumOfEvenFib.new(limit).sum_of_evens}"